apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorial
  labels:
    app.kubernetes.io/name: tutorial
    app.kubernetes.io/instance: tutorial
    app.kubernetes.io/component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tutorial
      app.kubernetes.io/instance: tutorial
      app.kubernetes.io/component: backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tutorial
        app.kubernetes.io/instance: tutorial
        app.kubernetes.io/component: backend
    spec:
      containers:
        - name: nginx
          image: registry.cyberspace.vn/tla/tutorial:v1.0.0
          ports:
          - containerPort: 80
          env:
          - name: DOMAIN
            value: "trolyao.org"
          - name: PORT
            value: "8080"
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: 200Mi