apiVersion: v1
kind: Service
metadata:
  name: tutorial-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: tutorial
    app.kubernetes.io/instance: tutorial
    app.kubernetes.io/component: backend
