global:
  env: production
  spec:
    project: default
    destination:
      server: https://kubernetes.default.svc
      namespace: default
    source:
      targetRevision: HEAD

argocdApplications:
  tutorial:
    repoURL: https://github.com/Hoangdao192/argocd.git
    disableAutomated: true
    disable: false
    name: tutorial
    path: apps/tutorial/overlay/production
    namespace: default
